package com.iia.projectsplanner.ui.theme

import androidx.compose.ui.graphics.Color


val md_theme_light_primary = Color(0xFF6750a4)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFeaddff)
val md_theme_light_onPrimaryContainer = Color(0xFF22005d)
val md_theme_light_secondary = Color(0xFF005ac5)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFd6e2ff)
val md_theme_light_onSecondaryContainer = Color(0xFF001943)
val md_theme_light_tertiary = Color(0xFF7d5260)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFffd8e4)
val md_theme_light_onTertiaryContainer = Color(0xFF31101d)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfcfcfc)
val md_theme_light_onBackground = Color(0xFF1f1a1b)
val md_theme_light_surface = Color(0xFFfcfcfc)
val md_theme_light_onSurface = Color(0xFF1f1a1b)
val md_theme_light_surfaceVariant = Color(0xFFe7e0ec)
val md_theme_light_onSurfaceVariant = Color(0xFF49454f)
val md_theme_light_outline = Color(0xFF79757f)
val md_theme_light_inverseOnSurface = Color(0xFFfaeeef)
val md_theme_light_inverseSurface = Color(0xFF352f30)
val md_theme_light_inversePrimary = Color(0xFFd0bcff)
val md_theme_light_shadow = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFd0bcff)
val md_theme_dark_onPrimary = Color(0xFF381e73)
val md_theme_dark_primaryContainer = Color(0xFF4f378b)
val md_theme_dark_onPrimaryContainer = Color(0xFFeaddff)
val md_theme_dark_secondary = Color(0xFFacc6ff)
val md_theme_dark_onSecondary = Color(0xFF002e6c)
val md_theme_dark_secondaryContainer = Color(0xFF004398)
val md_theme_dark_onSecondaryContainer = Color(0xFFd6e2ff)
val md_theme_dark_tertiary = Color(0xFFefb8c8)
val md_theme_dark_onTertiary = Color(0xFF4a2532)
val md_theme_dark_tertiaryContainer = Color(0xFF633b48)
val md_theme_dark_onTertiaryContainer = Color(0xFFffd8e4)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF1f1a1b)
val md_theme_dark_onBackground = Color(0xFFebe0e1)
val md_theme_dark_surface = Color(0xFF1f1a1b)
val md_theme_dark_onSurface = Color(0xFFebe0e1)
val md_theme_dark_surfaceVariant = Color(0xFF49454f)
val md_theme_dark_onSurfaceVariant = Color(0xFFcac4cf)
val md_theme_dark_outline = Color(0xFF948f99)
val md_theme_dark_inverseOnSurface = Color(0xFF1f1a1b)
val md_theme_dark_inverseSurface = Color(0xFFebe0e1)
val md_theme_dark_inversePrimary = Color(0xFF6750a4)
val md_theme_dark_shadow = Color(0xFF000000)

val seed = Color(0xFF6750a4)
val error = Color(0xFFba1b1b)